### ISSUE TITLE
calc() is missing ?

### ISSUE THREAD

**Issue by PubliAlex** [walbo/font-size-clamp#466]
Hello,

It seems that the calc() operator is missing when using your app

![image](https://user-images.githubusercontent.com/55833027/211144610-daca5bf2-119a-4071-a4f6-54dfc4c41fd4.png)

If I put that in CSS, I have errors, I have to use calc() for the value in the middle in order to make it works.

Best regards,

**Comment by Willem-Jaap** [comment]
The clamp function allows for its paramaters to be math functions.
See: https://developer.mozilla.org/en-US/docs/Web/CSS/clamp

**Comment by walbo** [comment]
Thanks @PubliAlex. As @Willem-Jaap said you shouldn't need to add clamp there.

From mdn:
> you can use addition, subtraction, multiplication, and division without using the calc() function itself
